// Turns content/index.html and content/ar.html into TypeScript string modules so the
// plan pages are bundled with the server code (no filesystem reads at runtime on Amplify).
// Runs automatically before `next dev` and `next build`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "src", "content");
mkdirSync(outDir, { recursive: true });

const NOINDEX = '<meta name="robots" content="noindex, nofollow">';

function prepare(html) {
  let out = html;
  // Language switch links inside the pages point at each other by file name;
  // the server replaces these placeholders with token-scoped URLs at request time.
  out = out.replace(/href="ar\.html"/g, 'href="{{AR_URL}}"').replace(/href="index\.html"/g, 'href="{{EN_URL}}"');
  if (!out.includes('name="robots"')) out = out.replace(/<head>/i, `<head>${NOINDEX}`);
  return out;
}

const pages = [
  ["index.html", "plan-en.ts", "PLAN_EN"],
  ["ar.html", "plan-ar.ts", "PLAN_AR"],
];

for (const [src, dest, name] of pages) {
  const html = readFileSync(join(root, "content", src), "utf8");
  const body = `// Generated by scripts/embed-plan.mjs from content/${src}. Do not edit by hand.\nexport const ${name}: string = ${JSON.stringify(prepare(html))};\n`;
  writeFileSync(join(outDir, dest), body);
  console.log(`embedded content/${src} -> src/content/${dest} (${Math.round(html.length / 1024)} KB)`);
}
